services:
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DB_HOST
        value: dpg-d73tq314tr6s73cfm95g-a
      - key: DB_USER
        value: todo_db_54m8_user
      - key: DB_PASSWORD
        value: qrYJCpC7dx0VOKLE13jtqXOkB2g5WcS5
      - key: DB_NAME
        value: todo_db_54m8
      - key: DB_SSL
        value: true
      - key: PORT
        value: 5000
  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo-02250374.onrender.com
